# name: CI

# on: [pull_request, push]
#
#
#
#
#
#
#
#
#
#
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout commit
#         uses: actions/checkout@v2

#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: "16.x"

#       - name: Cache NPM
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - name: Install Dependencies
#         run: npm ci

#       - name: Run linter
#         run: npm run lint

#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout commit
#         uses: actions/checkout@v2

#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: "16.x"

#       - name: Cache NPM
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - name: Install Dependencies
#         run: npm ci

#       - name: Run tests
#         run: npm run test
